name: my_movie
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management & DI
  flutter_bloc: ^9.1.1
  get_it: ^7.6.0

  # Navigation & Network
  go_router: ^14.0.0
  dio: ^5.4.0

  # Backend & Auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5

  # Local Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # UI, Fonts & Utilities
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  youtube_player_iframe: ^5.1.2
  connectivity_plus: ^6.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.6.0
  shimmer: ^3.0.0
  slang: ^4.14.0
  slang_flutter: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  slang_gpt: ^0.11.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

  adaptive_icon_background: "#E8445A"
  adaptive_icon_foreground: "assets/app_icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
flutter_native_splash:
  color: "#E8445A"

  image: assets/app_icon.png

  android_12:
    image: assets/app_icon.png
    color: "#E8445A"

  android: true
  ios: true

  fullscreen: true
